name: daily

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build review.go

    - name: Campus
      run: ./review 1144836532 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Rikako
      run: ./review 960647263 ${{secrets.SLACK_WEBHOOK_URL}} 
