name: daily

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build review.go

    - name: Campus Candidate
      run: ./review 1144836532 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Campus OB
      run: ./review 1255781175 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Rikako
      run: ./review 960647263 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Reaction
      run: ./review 674401547 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Resistance
      run: ./review 1034171119 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Charalarm
      run: ./review 1296641818 ${{secrets.SLACK_WEBHOOK_URL}} 

    - name: Write & Record
      run: ./review 1557408731 ${{secrets.WRITE_REC_SLACK_WEBHOOK_URL}} 
